### ISSUE TITLE
[Bug] angel3_orm_generator not working (Failed to precompile build script .dart_tool/build/entrypoint/build.dart)

### ISSUE THREAD

**Issue by ynnob** [dukefirehawk/angel#88]
### Error build_runner:

```
PS C:\Users\X\Documents\repos\helltax\database> dart run build_runner build --delete-conflicting-outputs
[INFO] Generating build script completed, took 306ms
[WARNING] ../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/angel3_orm_generator-7.1.0/lib/src/orm_build_context.dart:460:32: Error: The type 'PropertyAccessorElement?' of the getter 'RelationFieldImpl.getter' is not a subtype of the type 'PropertyAccessorElementImpl?' of the inherited setter 'PropertyInducingElementImpl.getter'.
 - 'PropertyAccessorElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-5.3.1/lib/dart/element/element.dart').
 - 'PropertyAccessorElementImpl' is from 'package:analyzer/src/dart/element/element.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-5.3.1/lib/src/dart/element/element.dart').
  PropertyAccessorElement? get getter => originalField.getter;
                               ^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-5.3.1/lib/src/dart/element/element.dart:5789:32: Context: This is the declaration of the setter 'PropertyInducingElementImpl.getter'.
  PropertyAccessorElementImpl? getter;
                               ^^^^^^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/angel3_orm_generator-7.1.0/lib/src/orm_build_context.dart:460:32: Error: The return type of the method 'RelationFieldImpl.getter' is 'PropertyAccessorElement?', which does not match the return type, 'PropertyAccessorElementImpl?', of the overridden method, 'PropertyInducingElementImpl.getter'.
 - 'PropertyAccessorElement' is from 'package:analyzer/dart/element/element.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-5.3.1/lib/dart/element/element.dart').
 - 'PropertyAccessorElementImpl' is from 'package:analyzer/src/dart/element/element.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-5.3.1/lib/src/dart/element/element.dart').
Change to a subtype of 'PropertyAccessorElementImpl?'.
  PropertyAccessorElement? get getter => originalField.getter;
                               ^
../../../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-5.3.1/lib/src/dart/element/element.dart:5789:32: Context: This is the overridden method ('getter').
  PropertyAccessorElementImpl? getter;
                               ^
[INFO] Precompiling build script... completed, took 792ms
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

### Setup
**models.dart**
```
import 'package:angel3_migration/angel3_migration.dart';
import 'package:angel3_model/angel3_model.dart';
import 'package:angel3_orm/angel3_orm.dart';
import 'package:angel3_serialize/angel3_serialize.dart';
import 'package:optional/optional.dart';
part 'models.g.dart';

@orm
@serializable
abstract class _User extends Model {
  String get email;
  String get passwordHash;
  bool? get emailConfirmed;
}
```

**pubspec.yaml**
```
dependencies:
  angel3_migration_runner: ^7.0.0
  angel3_orm: ^7.0.1
  angel3_orm_postgres: ^7.0.1
  collection: ^1.15.0
  optional: ^6.0.0
  postgres: ^2.5.2
  uuid: ^3.0.7

dev_dependencies:
  angel3_orm_generator: ^7.1.0
  build_runner: ^2.0.0
  lints: ^2.0.0
  test: ^1.22.1
```

### Note
When forking angel3 and resolving all packages the error exists in orm_build_context.dart:

```
[{
	"resource": "/c:/Users/X/Documents/repos/contribution/angel/packages/orm/angel_orm_generator/lib/src/orm_build_context.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "invalid_override",
		"target": {
			"$mid": 1,
			"external": "https://dart.dev/diagnostics/invalid_override",
			"path": "/diagnostics/invalid_override",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "'RelationFieldImpl.getter' ('PropertyAccessorElement? Function()') isn't a valid override of 'PropertyInducingElementImpl.getter' ('PropertyAccessorElementImpl? Function()').",
	"source": "dart",
	"startLineNumber": 460,
	"startColumn": 32,
	"endLineNumber": 460,
	"endColumn": 38,
	"relatedInformation": [
		{
			"startLineNumber": 5789,
			"startColumn": 32,
			"endLineNumber": 5789,
			"endColumn": 38,
			"message": "The member being overridden.",
			"resource": "/C:/Users/X/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/analyzer-5.3.1/lib/src/dart/element/element.dart"
		}
	]
}]
```

While the setup above fails, the following dependencies can generate models as expected:
```
dependencies:
  angel3_migration_runner: ^6.1.0
  angel3_orm: ^6.0.0
  angel3_orm_postgres: ^6.1.0
  collection: ^1.15.0
  optional: ^6.0.0
  postgres: ^2.5.2
  uuid: ^3.0.7

dev_dependencies:
  angel3_orm_generator: ^6.0.0
  build_runner: ^2.0.0
  lints: ^2.0.0
  test: ^1.22.1
```
